"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "packages/core/email/admin/src/translations/en.json",
    "translation": "packages/core/email/admin/src/translations/%locale%.json",
    "languages_mapping": {
      "locale": {
        "ar": "ar",
        "cs": "cs",
        "de": "de",
        "en-DK": "dk",
        "es-ES": "es",
        "fr": "fr",
        "id": "id",
        "it": "it",
        "ja": "ja",
        "ko": "ko",
        "ms": "ms",
        "nl": "nl",
        "pl": "pl",
        "pt-PT": "pt",
        "pt-BR": "pt-BR",
        "ru": "ru",
        "sk": "sk",
        "th": "th",
        "tr": "tr",
        "uk": "uk",
        "vi": "vi",
        "zh-TW": "zh",
        "zh-CN": "zh-Hans"
      }
    }
  }
]
